server:
  port: 8080

spring:
  datasource:
      url: jdbc:h2:mem:test
      driver-class-name: org.h2.Driver
      username: sa
      password: 

  jpa:
    hibernate:
      ddl-auto: create

file:
  path: C:/upload/